import Head from "next/head"

import Layout from "@/components/layout"
import PagedHeader from "@/components/page-header"
import PagedShell from "@/components/page-shell"

import type { NextPageWithLayout } from "./_app"

const DashboardPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PagedShell>
        <PagedHeader heading="Dashboard" text="Welcome back" />

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          Dashboard
        </div>
      </PagedShell>
    </>
  )
}

DashboardPage.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>
}

export default DashboardPage
