import Head from "next/head"
import { Authenticated } from "@refinedev/core"

import Layout from "@/components/layout"
import LoadingScreen from "@/components/loading"
import PagedHeader from "@/components/page-header"
import PagedShell from "@/components/page-shell"

import type { NextPageWithLayout } from "./_app"

const PlaylistsPage: NextPageWithLayout = () => {
  return (
    <Authenticated loading={<LoadingScreen />}>
      <Head>
        <title>Playlists | Anisong</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <PagedShell>
        <PagedHeader heading="Your playlists" />

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          Dashboard
        </div>
      </PagedShell>
    </Authenticated>
  )
}

PlaylistsPage.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>
}

export default PlaylistsPage
